name: Continuous Integration

on:
  push:
    paths:
      - "**.go"
      - "**.cue"
      - ".github/workflows/build.yaml"
      - "go.mod"
      - "go.sum"
    branches:
      - main
  pull_request:
    paths:
      - "**.go"
      - "**.cue"
      - ".github/workflows/build.yaml"
      - "go.mod"
      - "go.sum"
    branches:
      - main

env:
  DAGGER_LOG_FORMAT: plain

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    env:
      DAGGER_CACHE_BASE: "ci-build"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Expose GitHub Runtime"
        uses: crazy-max/ghaction-github-runtime@v1

      - name: "Set up dagger"
        uses: dagger/dagger-for-github@v3
        with:
          install-only: true

      - name: Sets env vars on push to main
        run: |
          echo "DAGGER_CACHE_TO=type=gha,mode=max,scope=${{env.DAGGER_CACHE_BASE}}-main" >> $GITHUB_ENV
          echo "DAGGER_CACHE_FROM=type=gha,scope=${{env.DAGGER_CACHE_BASE}}-main" >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Sets env vars on pull request
        run: |
          echo "DAGGER_CACHE_TO=type=gha,mode=max,scope=${{env.DAGGER_CACHE_BASE}}-${{github.event.number}}" >> $GITHUB_ENV
          echo "DAGGER_CACHE_FROM=type=gha,scope=${{env.DAGGER_CACHE_BASE}}-main type=gha,scope=${{env.DAGGER_CACHE_BASE}}-${{github.event.number}}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'pull_request' }}

      - name: Test
        run: dagger project update && dagger do build